---

- name: Fail if host configuration has not been loaded
  ansible.builtin.fail:
    msg: "Host configuration must be loaded from repo before extracting info"
  when: host_config is not defined

- name: Set hostname without domain
  ansible.builtin.set_fact:
    host_info_hostname: "{{ inventory_hostname.split('.')[0] }}"

- name: Get IOC user if specified
  ansible.builtin.set_fact:
    host_info_softioc_user: "{{ host_config.softioc_user }}"
  when: host_config.softioc_user is defined

- name: Set a default IOC user if not specified
  ansible.builtin.set_fact:
    host_info_softioc_user: "softioc"
  when: host_config.softioc_user is not defined

- name: Get IOC group if specified
  ansible.builtin.set_fact:
    host_info_softioc_group: "{{ host_config.softioc_group }}"
  when: host_config.softioc_group is defined

- name: Set a default IOC group if not specified
  ansible.builtin.set_fact:
    host_info_softioc_group: "n2sn-instadmin"
  when: host_config.softioc_group is not defined

- name: Create common directory if it does not exist
  ansible.builtin.file:
    path: "/epics/common"
    state: directory
    mode: "0775"
    owner: "{{ host_info_softioc_user }}"
    group: "{{ host_info_softioc_group }}"

- name: Get SCI interface ip
  ansible.builtin.set_fact:
    host_info_sci_intf_ip: "{{ ansible_default_ipv4.address }}"

- name: Print SCI IP
  ansible.builtin.debug:
    msg: "{{ host_info_sci_intf_ip }}"

- name: Try to automatically fetch network intf info
  when: host_config.host_epics_intf is not defined
  block:
    - name: Get individual digits from SCI IP
      ansible.builtin.set_fact:
        host_info_sci_intf_digits:
          "{{ ansible_default_ipv4.address.split('.') }}"

    - name: Set EPICS interface first three digits
      ansible.builtin.set_fact:
        host_info_epics_intf_first_three:
          "{{ host_info_sci_intf_digits[0] }}.\
          {{ host_info_sci_intf_digits[1] }}.\
          {{ host_info_sci_intf_digits[2] | int + 3 }}"

    - name: Set EPICS subnet
      ansible.builtin.set_fact:
        host_info_epics_subnet: "{{ host_info_epics_intf_first_three }}.255"

    - name: Set EPICS interface IP
      ansible.builtin.set_fact:
        host_info_epics_intf_ip:
          "{{ host_info_epics_intf_first_three }}.\
          {{ host_info_sci_intf_digits[3] }}"

- name: Set network information based on config
  when: host_config.host_epics_intf is defined
  block:
    - name: Set EPICS subnet
      ansible.builtin.set_fact:
        host_info_epics_subnet:
          "{{ host_epics_intf.split('.')[0:3] | join('.') }}.255"
      when: host_config.host_epics_intf != "127.0.0.1"

    - name: Set EPICS subnet if using localhost
      ansible.builtin.set_fact:
        host_info_epics_subnet: "{{ host_epics_intf }}"
      when: host_config.host_epics_intf == "127.0.0.1"

    - name: Set EPICS interface IP
      ansible.builtin.set_fact:
        host_info_epics_intf_ip: "{{ host_config.host_epics_intf }}"

- name: Print EPICS interface IP
  ansible.builtin.debug:
    msg: "{{ host_info_epics_intf_ip }}"

- name: Create empty list to store IOC names
  ansible.builtin.set_fact:
    host_info_ioc_list: []

- name: Get list of IOC names from loaded config
  ansible.builtin.set_fact:
    host_info_ioc_list: >-
      "{{ host_config |
          dict2items |
          selectattr('value', 'mapping') |
          selectattr('value.type', 'defined') |
          map(attribute='key') | list }}"
