---
type: ioc_type()
environment: map(any(str(), int(), num()), key=str())
substitutions: map(any(list(include("substitution")), include("template")), key=str(), required=False) # yamllint disable-line rule:line-length
executable: str(required=False)
required_module: str(required=False)

---

template:
  templates: list(include("substitution"))
  template_macros: str(required=False)
  load_as_template: bool(required=False)

substitution:
  filepath: str()
  pattern: list(str)
  instances: list(list(any(str(), int(), num())))
