adkinetix_1c03d32:
  name: adkinetix
  url: https://github.com/NSLS2/ADKinetix
  version: 1c03d32
  include_base_ad_config: true
  module_deps:
    - adcore_60080dc
    - adcompvision_9750d13
    - adpluginbar_448d96b
    - ffmpeg_server_07c570f
