---
deploy_ioc_use_common: false
deploy_ioc_use_ad_common: true
deploy_ioc_required_module: adcore_60080dc
deploy_ioc_executable: axisApp
deploy_ioc_device_specific_env:
  ADAXIS: "/epics/modules/ADAxis"
  PORT: "AXIS1"
  QSIZE: 20
  XSIZE: 4096
  YSIZE: 4096
  NCHANS: 2048
  CBUFFS: 500
  EPICS_DB_INCLUDE_PATH: "$(ADCORE)/db:$(ADAXIS)/db"
